name: RaftBattle
version: '${project.version}'
main: me.stephenminer.raftbattle.RaftBattle

commands:
  raftmap:
  raftjoin:
    aliases:
      - rjoin
  raftquit:
    aliases:
      - rleave
  raftreload: